
# AUTOMATICALLY GENERATED BY THE PDL TOPLEVEL Makefile.PL.
# DO NOT HAND-EDIT - CHANGES WILL BE LOST UPON YOUR NEXT
#  'perl Makefile.PL'!!!
package PDL::Config;
use strict;
use warnings;
%PDL::Config = %{
{
  'FITS_LEGACY' => 1,
  'GD_DEFINE' => '',
  'GD_INC' => undef,
  'GD_LIBS' => undef,
  'GSL_INC' => undef,
  'GSL_LIBS' => undef,
  'HDF_INC' => undef,
  'HDF_LIBS' => undef,
  'HIDE_TRYLINK' => 1,
  'HTML_DOCS' => 1,
  'MALLOCDBG' => {
    'include' => '',
    'libs' => ''
  },
  'MINUIT_LIB' => undef,
  'OPTIMIZE' => undef,
  'PDLDOC_IGNORE_AUTOLOADER' => 0,
  'PDL_BUILD_VERSION' => undef,
  'PDL_CONFIG_VERSION' => '0.005',
  'POGL_WINDOW_TYPE' => 'glut',
  'POSIX_THREADS_INC' => undef,
  'POSIX_THREADS_LIBS' => undef,
  'WITH_DEVEL_REPL' => 1,
  'WITH_GD' => 0,
  'WITH_HDF' => 0,
  'WITH_MINUIT' => 0,
  'WITH_POSIX_THREADS' => 1
}
};
1;
