#!/usr/bin/perl
use warnings;
use strict;
use Getopt::Long;
use experimental 'signatures';
use Data::Dumper;

=pod

=head1 NAME 

  hogwarts

=head1 USAGE

 hogwarts [OPTION] [Student First Name]

 -s, --spell   favorite spell. 
 -h, --house   the house of the school
 -r, --rival   The person who the named character will attack
 -d, --doc     For instructions on how to get documentation.

=head1 DESCRIPTION

  This utility is limited to a few characters from the Harry Potter universe.

  Harry who is in Gryffindor House and likes to use Expelliarmus. 
  Hermione who is in Gryffindor House and likes Wingardium Leviosa. 
  Voldemort who is in Sytherin House and likes Avada Kedavra. 
  Snape who is in Sytherin House and likes Serpensortia. 

=cut

if (!$ARGV[0]) {
  die "Error! USAGE: hogwarts [OPTION] [Student First Name]\n";
}

my $spell = "";
my $house = "";
my $rival = "";
my $doc;
my @friends;

GetOptions("spell=s" => \$spell,
           "house=s" => \$house,
           "rival=s" => \$rival,
           "friends=s" => \@friends,
           "doc"    => \$doc) or exit 1;

if (defined $doc) {
  print "Get documentation by:\nUSAGE: perldoc hogwarts\n";
  exit;
}


my $name = $ARGV[0];

if ($name eq "Harry") {
  $spell = $spell?$spell:"Expelliarmus";
  $house = "Gryffindor";
  $rival = $rival?$rival:"Malfoy";
  @friends = @friends?@friends:"Ron Hermione";
}
elsif ($name eq "Hermione") {
  $spell = $spell?$spell:"Wingardium Leviosa";
  $house = "Gryffindor";
  $rival = $rival?$rival:"Bellatrix";
  @friends = @friends?@friends:"Ron Harry";
}
elsif ($name eq "Voldemort") {
  $spell = $spell?$spell:"Avada Kedavra";
  $house = "Slytherin";
  $rival = $rival?$rival:"Dumbledore";
  @friends = @friends?@friends:"Death Eaters";
}
elsif ($name eq "Snape") {
  $spell = $spell?$spell:"Serpensortia";
  $house = "Slytherin";
  $rival = $rival?$rival:"James";
  @friends = @friends?@friends:"Lily";
}

print "$name from $house house attacked $rival with the $spell spell\n";
print "$name has friends: @friends\n";
